### ISSUE TITLE
"low is out of bounds for int32" when building python binding in i386 platform

### ISSUE THREAD

**Issue by czchen** [wesm/feather#105]
See https://bugs.debian.org/819997, the following error message show up:

```
  ======================================================================
  ERROR: test_integer_no_nulls (feather.tests.test_reader.TestFeatherReader)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/«PKGBUILDDIR»/feather/tests/test_reader.py", line 126, in test_integer_no_nulls
      size=num_values)
    File "mtrand.pyx", line 1260, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:14127)
  ValueError: low is out of bounds for int32

  ----------------------------------------------------------------------
  Ran 14 tests in 0.099s

  FAILED (errors=1)
```

**Comment by wesm** [comment]
I see -- take a look at https://github.com/wesm/feather/blob/master/python/feather/tests/test_reader.py#L125

**Comment by wesm** [comment]
Closing. If you need i386 support for Feather, I suggest you open JIRAs and work within the Apache Arrow project. I haven't tried building or packaging Arrow on 32-bit systems yet
