### ISSUE TITLE
Resolve ASAN/UBSAN issues

### ISSUE THREAD

**Issue by hadley** [wesm/feather#163]
http://www.stats.ox.ac.uk/pub/bdr/memtests/gcc6-ASAN/feather/tests/testthat.Rout.fail
http://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/feather/tests/testthat.Rout

Most are alignment issues which @jeroenooms thinks are not important.

Two that look like they might be important to me are:

```
=================================================================
==44840==ERROR: AddressSanitizer: new-delete-type-mismatch on 0x61000002b640 in thread T0:
  object passed to delete has wrong type:
  size of the allocated type:   192 bytes;
  size of the deallocated type: 104 bytes.
    #0 0x7fbd304c3900 in operator delete(void*, unsigned long) (/usr/local/gcc6/lib64/libasan.so.3+0xc3900)
    #1 0x7fbd2221332b in std::default_delete<feather::Column>::operator()(feather::Column*) const /usr/local/gcc6/include/c++/7.0.0/bits/unique_ptr.h:76
    #2 0x7fbd2221332b in std::unique_ptr<feather::Column, std::default_delete<feather::Column> >::~unique_ptr() /usr/local/gcc6/include/c++/7.0.0/bits/unique_ptr.h:236
    #3 0x7fbd2221332b in colnamesAsCharacterVector(feather::TableReader const&) /data/gannet/ripley/R/packages/tests-60/feather/src/feather-read.cpp:56
    #4 0x7fbd222151d1 in openFeather(std::string const&) /data/gannet/ripley/R/packages/tests-60/feather/src/feather-read.cpp:72
    #5 0x7fbd221ff321 in feather_openFeather /data/gannet/ripley/R/packages/tests-60/feather/src/RcppExports.cpp:27
```

And maybe this one too?

```
feather-write.cpp:16:44: runtime error: null pointer passed as argument 1, which is declared to never be null
feather/io.cc:246:33: runtime error: null pointer passed as argument 1, which is declared to never be null
feather-types.cpp:134:40: runtime error: load of misaligned address 0x7f4097d02005 for type 'const int32_t', which requires 4 byte alignment
0x7f4097d02005: note: pointer points here
 45 41 31 0b 00 00 00  00 10 00 00 00 10 00 00  00 10 00 00 00 1e 00 00  00 74 68 69 73 20 69 73  20
```

**Comment by jeroenooms** [comment]
Someone looking into this yet? I can put some time in this.

**Comment by hadley** [comment]
Yeah, it'd be great if you could have a look.

**Comment by jeroenooms** [comment]
Here is the null pointer one: 

```r
> test_that("preserves logical vector of length 0", {
+   x <- logical()
+   expect_identical(roundtrip_vector(x), x)
+ })
feather-write.cpp:16:44: runtime error: null pointer passed as argument 1, which is declared to never be null
feather/io.cc:246:33: runtime error: null pointer passed as argument 1, which is declared to never be null
```

**Comment by jeroenooms** [comment]
The overflow appears for the NA in factors:

```r
> df <- data.frame(x = factor(c("abc", "def", NA)))
> write_feather(df, tempfile())
feather-write.cpp:114:31: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'
```

**Comment by wesm** [comment]
This should be resolved?

**Comment by jeroenooms** [comment]
I confirm that as of https://github.com/wesm/feather/commit/002c79822a77379c5ea395c83474779863db9712 all UBSAN problems (including misaligned address warnings) have been resolved. This issue can be closed. Great work!

**Comment by wesm** [comment]
Great! I would have hoped this would be the case, as the only non-padded / aligned writes in the codebase are the 8 bytes at the foot of the file (the metadata size and the magic bytes).

**Comment by martin00001313** [comment]
Hi all.
Can I run asan and ubsan together and how? (in gcc6.2)

Regards,
Martin.
