### ISSUE TITLE
TypeError: chown() missing 1 required positional argument: 'numeric_owner'

### ISSUE THREAD

**Issue by femtotrader** [wesm/feather#195]
Hello,

`$ pip install feather`

raises

```
Collecting feather
  Using cached feather-0.9.1dev.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/tmp5lr5upto
    Traceback (most recent call last):
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/setup.py", line 3, in <module>
        distribute_setup.use_setuptools()
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-7sc4sgy_/feather/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
```

I'm using Anaconda Python under Mac OS X

```
$ python --version
Python 3.5.1 :: Anaconda custom (x86_64)
```

Any idea ?

Kind regards

**Comment by femtotrader** [comment]
I think that wasn't the right feather!
I didn't read https://github.com/wesm/feather/tree/master/python
So I'm closing

**Comment by wesm** [comment]
Feel free to ping the other project owner to see if they'll give us the `feather` PyPI real estate

**Comment by wesm** [comment]
Wow that's crazy that that tiny package tries to bootstrap distribute for you
