### ISSUE TITLE
uint64 in python lib can't actually deal with uint values bigger than uint32.max

### ISSUE THREAD

**Issue by bryonjacob** [wesm/feather#288]
The python library can write `uint64` (also called `u8` in the python code) values, but it actually fails with values whose internal representation is bigger than will fit in 4 bytes.

Here's my reproduction from a REPL:

```python
# import the things
>>> import numpy as np
>>> import feather as f
>>> import pandas as pd

# grab type info for uint32 and uint64
>>> uint32 = np.iinfo('uint32')
>>> uint64 = np.iinfo('uint64')

# write out a uint32 data frame - works okay
>>> f.write_dataframe(pd.DataFrame({'a':[uint32.min, 0, uint32.max]}), '/tmp/out32.feather')

# write out a uint64 data frame - we have an issue based on pd.lib.infer_dtype
>>> f.write_dataframe(pd.DataFrame({'a':[uint64.min, 0, uint64.max]}), '/tmp/out64.feather')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "feather/api.py", line 56, in write_dataframe
    raise ValueError(msg)
ValueError: cannot serialize column 0 named a with dtype integer
```

https://github.com/wesm/feather/blob/master/python/feather/api.py#L42-L56

**Comment by wesm** [comment]
Closing as this is addressed by the `pyarrow` package now
