### ISSUE TITLE
pip install without Cython throwing error

### ISSUE THREAD

**Issue by nateGeorge** [wesm/feather#289]
When installing via pip (for me on Ubuntu 16.04 x64), it gives the error:

`pip install feather-format`

```
Collecting feather-format
  Downloading feather-format-0.3.1.tar.gz (956kB)
    100% |████████████████████████████████| 962kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HJq3z_/feather-format/setup.py", line 19, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
```

if cython isn't installed.  This is easy enough to fix by doing

`pip install cython`

but it would be nice if when installing feather, it took care of that for you.

**Comment by nateGeorge** [comment]
Just noticed this is taken care of with #256 and #260
