### ISSUE TITLE
Pip install - HTTP Error 403: SSL is required

### ISSUE THREAD

**Issue by geofflee** [wesm/feather#322]
I get the following error when trying to install feather from pip. It seems to be related to this: https://mail.python.org/pipermail/distutils-sig/2017-October/031714.html

```
# pip install feather
Collecting feather
  Downloading feather-0.9.1dev.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-build-k2kt2okp/feather/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k2kt2okp/feather/setup.py", line 3, in <module>
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-k2kt2okp/feather/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-k2kt2okp/feather/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-build-k2kt2okp/feather/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k2kt2okp/feather/
```

**Comment by xhochy** [comment]
You need to install `feather-format`, `feather` is a different project.

**Comment by geofflee** [comment]
Ah, ok! That solves it.

Perhaps you should put a note of that in your README.md. It's a pretty easy mistake to make for somebody who is relatively new to Python and this project.
