### ISSUE TITLE
Python ImportError on Ubuntu 18.04

### ISSUE THREAD

**Issue by cpiscos** [wesm/feather#343]
I get this error when importing feather which was installed through conda:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/feather/__init__.py", line 17, in <module>
    from feather.api import (read_dataframe, write_dataframe,
  File "/home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/feather/api.py", line 15, in <module>
    from pyarrow.feather import (read_feather as read_dataframe,  # noqa
  File "/home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/pyarrow/__init__.py", line 47, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: /home/chris/miniconda3/envs/ai/lib/python3.6/site-packages/pyarrow/../../../libparquet.so.1: undefined symbol: _ZNK5boost16re_detail_10650131cpp_regex_traits_implementationIcE9transformEPKcS4_

```

**Comment by xhochy** [comment]
This should be fixed now, please try to reinstall `arrow-cpp`, `parquet-cpp` and `pyarrow` from `conda-forge`.

**Comment by wesm** [comment]
I just confirmed that a fresh install from conda-forge works fine. Closing this issue

**Comment by cpiscos** [comment]
Yes, it's working now. Thank you!
