### ISSUE TITLE
Error writing pandas dataframe `is_datetime64_any_dtype`

### ISSUE THREAD

**Issue by petrjanda** [wesm/feather#90]
Getting the following error when writing dataframe to feather:

```
Traceback (most recent call last):
  File "0_cleanup.py", line 48, in <module>
    feather.write_dataframe(df, args.out_file)
  File "/usr/local/lib/python3.4/site-packages/feather/api.py", line 35, in write_dataframe
    writer.write_array(name, col)
  File "feather/ext.pyx", line 85, in feather.ext.FeatherWriter.write_array (feather/ext.cpp:2066)
AttributeError: 'module' object has no attribute 'is_datetime64_any_dtype'
```

All columns are of the type `dtype('float64')`. Is there anything I am doing wrong?

**Comment by petrjanda** [comment]
To showcase the problem, it doesn't work even with simple dataframes:

```
  1 import pandas as pd
  2 import feather
  3
  4 df = pd.DataFrame([0,1])
  5
  6 feather.write_dataframe(df, 'df.feather')
```

**Comment by jreback** [comment]
```
In [1]: import feather as fth

In [2]: import pandas as pd

In [3]: pd.__version__
Out[3]: '0.16.2'

In [4]: df = pd.DataFrame([0,1])

In [5]: fth.write_dataframe(df, 'df.fth')
AttributeError: 'module' object has no attribute 'is_datetime64_any_dtype'
```

```
In [1]: import feather as fth

In [2]: import pandas as pd

In [3]: pd.__version__
Out[3]: u'0.18.0'

In [1]: import feather as fth

In [2]: import pandas as pd

In [3]: pd.__version__
Out[3]: u'0.18.0'

In [5]: df = pd.DataFrame([0,1])

In [6]: fth.write_dataframe(df, 'df.fth')

```

you need at least ``pandas >= 0.17.0``.

feather should prob raise an ``ImportError`` if this is not the case.

**Comment by petrjanda** [comment]
Brilliant! Upgrade to `pandas==0.18.0` solved the problem as you advised. Thanks!
